### ISSUE TITLE
HUD example compiles but crashes

### ISSUE THREAD

**Issue by faide** [paked/engi#144]
This crashes as soon as I launch the example with the following traceback:

```bash
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x7f90bf226ff0]

runtime stack:
runtime.throw(0x7bac40, 0x2a)
	/home/faide/tools/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/home/faide/tools/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x60d8e0, 0xc8200c7ad0, 0x0)
	/home/faide/tools/go/src/runtime/cgocall.go:120 +0x11b fp=0xc8200c7a88 sp=0xc8200c7a58
github.com/go-gl/gl/v2.1/gl._Cfunc_glowDrawElements(0x7f90bef73760, 0x600000004, 0x1403, 0x0)
	github.com/go-gl/gl/v2.1/gl/_obj/_cgo_gotypes.go:12227 +0x35 fp=0xc8200c7ad0 sp=0xc8200c7a88
github.com/go-gl/gl/v2.1/gl.DrawElements(0x600000004, 0xc800001403, 0x0)
	/home/faide/go/src/github.com/go-gl/gl/v2.1/gl/package.go:19385 +0x45 fp=0xc8200c7af8 sp=0xc8200c7ad0
github.com/paked/webgl.(*Context).DrawElements(0xc8200f6000, 0x4, 0x6, 0x1403, 0x0)
	/home/faide/go/src/github.com/paked/webgl/webgl_gl2.go:775 +0x42 fp=0xc8200c7b18 sp=0xc8200c7af8
github.com/paked/engi.(*HUDShader).flush(0xc8200be000)
	/home/faide/go/src/github.com/paked/engi/shaders.go:289 +0x168 fp=0xc8200c7b58 sp=0xc8200c7b18
github.com/paked/engi.(*HUDShader).Post(0xc8200be000)
	/home/faide/go/src/github.com/paked/engi/shaders.go:294 +0x21 fp=0xc8200c7b68 sp=0xc8200c7b58
github.com/paked/engi.(*RenderSystem).Post(0xc82000e420)
	/home/faide/go/src/github.com/paked/engi/render.go:291 +0xce fp=0xc8200c7ca0 sp=0xc8200c7b68
github.com/paked/engi/ecs.(*World).Update(0xc820014720, 0x0)
	/home/faide/go/src/github.com/paked/engi/ecs/world.go:121 +0x2d5 fp=0xc8200c7d90 sp=0xc8200c7ca0
github.com/paked/engi.RunIteration()
	/home/faide/go/src/github.com/paked/engi/engi_glfw.go:194 +0x53 fp=0xc8200c7da8 sp=0xc8200c7d90
github.com/paked/engi.runLoop(0x7f90bc69f360, 0xc6fb60, 0x400)
	/home/faide/go/src/github.com/paked/engi/engi_glfw.go:226 +0xd9 fp=0xc8200c7e70 sp=0xc8200c7da8
github.com/paked/engi.Open(0x0, 0x71d4b0, 0x8, 0x0, 0x400, 0x280, 0x0, 0x0, 0x7f90bc69f360, 0xc6fb60)
	/home/faide/go/src/github.com/paked/engi/engi.go:68 +0xf4 fp=0xc8200c7ea0 sp=0xc8200c7e70
main.main()
	/home/faide/go/src/github.com/paked/engi/demos/hud/hud.go:108 +0xab fp=0xc8200c7f50 sp=0xc8200c7ea0
runtime.main()
	/home/faide/tools/go/src/runtime/proc.go:111 +0x2b0 fp=0xc8200c7fa0 sp=0xc8200c7f50
runtime.goexit()
	/home/faide/tools/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc8200c7fa8 sp=0xc8200c7fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/faide/tools/go/src/runtime/asm_amd64.s:1721 +0x1
```

if I suppress the call to ```w.AddEntity(hudBg)``` it works so I suspect something in ```generateHUDBackground``` but I can't see what really differs from ```generateBackground``` which works fine.

**Comment by paked** [comment]
What version of Go are you using?

**Comment by faide** [comment]
ATM go 1.5.3

**Comment by faide** [comment]
If I try with go 1.6 I get
```bash
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running, locked to thread]:
panic(0x6d7c60, 0xc82000a610)
	/home/faide/tools/go/src/runtime/panic.go:464 +0x3e6
github.com/go-gl/gl/v2.1/gl.ShaderSource(0x100000001, 0xc8200340c0, 0x0)
	/home/faide/go/src/github.com/go-gl/gl/v2.1/gl/package.go:24310 +0x4c
github.com/paked/webgl.(*Context).ShaderSource(0xc8200f4000, 0xc82000a5d8, 0x96aba0, 0x1e9)
	/home/faide/go/src/github.com/paked/webgl/webgl_gl2.go:620 +0xc3
github.com/paked/engi.LoadShader(0x96aba0, 0x1e9, 0x96a3e0, 0x115, 0x0)
	/home/faide/go/src/github.com/paked/engi/assets.go:136 +0x76
github.com/paked/engi.(*DefaultShader).Initialize(0xc47268, 0x4420000044800000)
	/home/faide/go/src/github.com/paked/engi/shaders.go:73 +0x45
github.com/paked/engi.(*RenderSystem).New(0xc82000e480, 0xc820014690)
	/home/faide/go/src/github.com/paked/engi/render.go:209 +0x1a3
github.com/paked/engi/ecs.(*World).AddSystem(0xc820014690, 0x7f99024b6450, 0xc82000e480)
	/home/faide/go/src/github.com/paked/engi/ecs/world.go:65 +0x35
main.(*Game).Setup(0xc62bf8, 0xc820014690)
	/home/faide/go/src/github.com/paked/engi/demos/hud/hud.go:78 +0x87
github.com/paked/engi.SetScene(0x7f99024b6360, 0xc62bf8, 0xc820014600)
	/home/faide/go/src/github.com/paked/engi/scene.go:86 +0x2a7
github.com/paked/engi.RunPreparation(0x7f99024b6360, 0xc62bf8)
	/home/faide/go/src/github.com/paked/engi/engi_glfw.go:215 +0x30f
github.com/paked/engi.runLoop(0x7f99024b6360, 0xc62bf8, 0x400)
	/home/faide/go/src/github.com/paked/engi/engi_glfw.go:219 +0x3d
github.com/paked/engi.Open(0x0, 0x71ad00, 0x8, 0x0, 0x400, 0x280, 0x0, 0x0, 0x7f99024b6360, 0xc62bf8)
	/home/faide/go/src/github.com/paked/engi/engi.go:68 +0xf4
main.main()
	/home/faide/go/src/github.com/paked/engi/demos/hud/hud.go:108 +0xac
```

**Comment by paked** [comment]
Yeah, 1.6 broke [go-gl](https://github.com/go-gl/gl) (a library that we heavily depend on). Hopefully they will have a fix out soon.

In the meantime, I'll try and debug this and get back to you when I have something new!

**Comment by paked** [comment]
Alright. So it looks like e8d15d8b2af5087e65eaa47ed7a645994477254b broke the HUD. @EtienneBruines Do you have time to take point on fixing this (I haven't touched the shaders in forever.)?

**Comment by EtienneBruines** [comment]
@faide Thank you for reporting this issue. I will have time for this tonight (in about 6 hrs). Should be a relatively easy fix, though. 

W.r.t. the Go 1.6, there has been made some progress (not by me) [here](https://github.com/go-gl/gl/issues/31#issuecomment-186541351).

**Comment by EtienneBruines** [comment]
OK, this is weird. Using the code from `master`, and `go1.5.2`, I'm seeing no runtime error whatsoever. (using `go run hud.go`)

May I ask how you're attempting to run it, @faide?

Are you able to replicate this bug, @paked?

@faide I see the callback goes all the way back to `shaders.go:289`, which is a specific shader defined for the HUD. This would explain why there's a difference between the HUD and the background. So this would have nothing to do with the example `hud.go`. I'm not quite sure yet why this would result in a GPU/OpenGL crash... (which is what's happening)

**Comment by paked** [comment]
@EtienneBruines I was able to replicate this on OS X Yosemite, `go1.5.3`.

I'll try on Arch Linux now.

**Comment by EtienneBruines** [comment]
Then it must be a glitch on my part, causing it to "not crash". Investigating...

**Comment by faide** [comment]
I am on Ubuntu 

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

here is a transcript of what I do once inside engi source code

```bash
$ git pull
Already up-to-date.
$ cd demos/hud/
$ go build -a
$ ./hud
... same crash as reported ...
```

I tried also with go 1.5.2 and got the same result. If you need any more system info (libs, kernel, whatever...) just ask

I verified:
github.com/paked/webgl (up to date)
github.com/go-gl/gl (up to date)

**Comment by EtienneBruines** [comment]
Thank you @faide. 

Could you run `glxheads` in the terminal? This outputs some variables.

**Comment by EtienneBruines** [comment]
@faide Could you try this branch? https://github.com/EtienneBruines/engi/tree/hotfix_144

Probably something like:
```
git remote add EtienneBruines https://github.com/EtienneBruines/engi.git
git fetch EtienneBruines
git checkout EtienneBruines/hotfix_144
```

**Comment by faide** [comment]
First part of the answer

```bash
$ glxheads :0
Name: :0
  Display:     0x2256010
  Window:      0x1600002
  Context:     0x2264c10
  GL_VERSION:  3.0 Mesa 10.1.3
  GL_VENDOR:   Intel Open Source Technology Center
  GL_RENDERER: Mesa DRI Intel(R) Ivybridge Mobile
```

**Comment by faide** [comment]
I updated to your hotfix
and still crashes (github.com/paked/engi/shaders.go:255 being the last engi code called)

```bash
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x7ff991c47ff0]

runtime stack:
runtime.throw(0x7ba060, 0x2a)
	/home/faide/tools/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/home/faide/tools/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x60cfd0, 0xc820745ae0, 0x0)
	/home/faide/tools/go/src/runtime/cgocall.go:120 +0x11b fp=0xc820745a98 sp=0xc820745a68
github.com/go-gl/gl/v2.1/gl._Cfunc_glowDrawElements(0x7ff991994760, 0x600000004, 0x7ff900001403, 0x0)
	github.com/go-gl/gl/v2.1/gl/_obj/_cgo_gotypes.go:12233 +0x35 fp=0xc820745ae0 sp=0xc820745a98
github.com/go-gl/gl/v2.1/gl.DrawElements(0x600000004, 0xbf80000000001403, 0x0)
	/home/faide/go/src/github.com/go-gl/gl/v2.1/gl/package.go:19385 +0x45 fp=0xc820745b08 sp=0xc820745ae0
github.com/paked/webgl.(*Context).DrawElements(0xc8200f8000, 0x4, 0x6, 0x1403, 0x0)
	/home/faide/go/src/github.com/paked/webgl/webgl_gl2.go:775 +0x42 fp=0xc820745b28 sp=0xc820745b08
github.com/paked/engi.(*HUDShader).Draw(0xc820064150, 0xc8205c6f10, 0xc8205c6f50, 0xbf800000bf800000, 0xc800000000)
	/home/faide/go/src/github.com/paked/engi/shaders.go:255 +0x215 fp=0xc820745b68 sp=0xc820745b28
github.com/paked/engi.(*RenderSystem).Post(0xc82000e420)
	/home/faide/go/src/github.com/paked/engi/render.go:286 +0x415 fp=0xc820745ca0 sp=0xc820745b68
github.com/paked/engi/ecs.(*World).Update(0xc820014840, 0x0)
	/home/faide/go/src/github.com/paked/engi/ecs/world.go:121 +0x2d5 fp=0xc820745d90 sp=0xc820745ca0
github.com/paked/engi.RunIteration()
	/home/faide/go/src/github.com/paked/engi/engi_glfw.go:194 +0x53 fp=0xc820745da8 sp=0xc820745d90
github.com/paked/engi.runLoop(0x7ff98f0c0360, 0xc6eb60, 0x400)
	/home/faide/go/src/github.com/paked/engi/engi_glfw.go:226 +0xd9 fp=0xc820745e70 sp=0xc820745da8
github.com/paked/engi.Open(0x0, 0x71c9c0, 0x8, 0x0, 0x400, 0x280, 0x0, 0x0, 0x7ff98f0c0360, 0xc6eb60)
	/home/faide/go/src/github.com/paked/engi/engi.go:68 +0xf4 fp=0xc820745ea0 sp=0xc820745e70
main.main()
	/home/faide/go/src/github.com/paked/engi/demos/hud/hud.go:108 +0xab fp=0xc820745f50 sp=0xc820745ea0
runtime.main()
	/home/faide/tools/go/src/runtime/proc.go:111 +0x2b0 fp=0xc820745fa0 sp=0xc820745f50
runtime.goexit()
	/home/faide/tools/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820745fa8 sp=0xc820745fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/faide/tools/go/src/runtime/asm_amd64.s:1721 +0x1
```

**Comment by EtienneBruines** [comment]
I'm attempting to see if the `HUDShader` is to blame or not. Could you try again? (new commit in that branch)

(note that the goal of this test is not to see if it *works*, but to see whether or not it will *crash*)

**Comment by paked** [comment]
@EtienneBruines That does not crash for me now.

**Comment by EtienneBruines** [comment]
OK, good to know. Then it's definitely the `HUDShader`.

**Comment by EtienneBruines** [comment]
Does the new commit fix the issue? (it works as intended on my pc, and if it doesn't crash, then we're all happy :-).

**Comment by paked** [comment]
@EtienneBruines Works for me!

**Comment by EtienneBruines** [comment]
@faide Thank you for reporting this issue. 

If it turns out that #145 didn't fix your issue, feel free to reopen. Happy to help.

**Comment by faide** [comment]
I confirm it does not crash anymore
